<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net6.0</TargetFramework>
	<LangVersion>10.0</LangVersion>
    <OutputType>Exe</OutputType>
	<AnalysisMode>All</AnalysisMode>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.13.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MaximPractice\MaximPractice.csproj" />
  </ItemGroup>
</Project>
